USER-SUPPLIED VALUES:
autoDirectNodeRoutes: true
enable-bgp-control-plane:
  enabled: true
ingressController:
  Enabled: true
installCRDs: true
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: 10.42.0.0/16
ipv4:
  enabled: true
ipv4NativeRoutingCIDR: 10.42.0.0/16
k8sClientRateLimit:
  burst: 100
  qps: 50
k8sServiceHost: 100.95.112.47
k8sServicePort: 6443
kubeProxyReplacement: true
l2announcements:
  enabled: true
  leaseDuration: 3s
  leaseRenewDeadline: 1s
  leaseRetryPeriod: 200ms
loadBalancer:
  mode: snat
operator:
  replicas: 1
  prometheus:
    enabled: true
    port: 9963
    serviceMonitor:
      enabled: false
prometheus:
  enabled: true
  port: 9962
routingMode: native
