---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cilium-agent
  namespace: monitoring
  labels:
    release: my-kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: cilium
  podMetricsEndpoints:
    - port: prometheus
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: cilium-operator
  namespace: monitoring
  labels:
    release: my-kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      io.cilium/app: operator
  podMetricsEndpoints:
    - port: prometheus
      path: /metrics
      interval: 30s
