all:
  vars:
    ansible_user: tadeu
    ansible_become: true
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

  children:
    k3s_master:
      hosts:
        raspberrypi4-5:
          ansible_host: 192.168.1.106

    k3s_workers:
      hosts:
        raspberrypi4-1:
          ansible_host: 192.168.1.102
        raspberrypi4-3:
          ansible_host: 192.168.1.103
        raspberrypi4-4:
          ansible_host: 192.168.1.105

    k3s_nodes:
      children:
        k3s_master:
        k3s_workers:
