apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: cluster-example-pooler
  namespace: postgres
spec:
  cluster:
    name: cnpg-cluster
  
  instances: 2
  type: rw  # Read-write pooler
  
  pgbouncer:
    parameters:
      max_client_conn: "1000"  # Total client connections
      default_pool_size: "25"  # Pool size per database
      server_reset_query: "DISCARD ALL"
      server_check_delay: "30"
      server_check_query: "SELECT 1"
      server_lifetime: "3600"
      server_idle_timeout: "600"
