apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: cnpg
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 100m
      memory: 256Mi
    default:
      cpu: 1000m
      memory: 1Gi
