apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: traefik
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 50m
      memory: 64Mi
    default:
      cpu: 300m
      memory: 128Mi
