apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: kyverno
spec:
  limits:
  - type: Container
    defaultRequest:
      cpu: 50m
      memory: 64Mi
    default:
      cpu: 500m
      memory: 256Mi
