---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datadog-agent-redis-secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
  resourceNames: ["argocd-redis"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datadog-agent-redis-secret-reader-binding
subjects:
- kind: ServiceAccount
  name: datadog-agent
  namespace: default
roleRef:
  kind: ClusterRole
  name: datadog-agent-redis-secret-reader
  apiGroup: rbac.authorization.k8s.io

