---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: datadog-read-redis-secret
  namespace: argocd
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["argocd-redis"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: datadog-read-redis-secret-binding
  namespace: argocd
subjects:
- kind: ServiceAccount
  name: datadog-agent   # datadog-agent user
  namespace: default   
roleRef:
  kind: Role
  name: datadog-read-redis-secret
  apiGroup: rbac.authorization.k8s.io

